jobs:
  include:
    - os: linux
      dist: bionic
      sudo: required
      language: minimal
      services: 
        - docker
      install:
        - docker build -t wangyinz/mspass .
      script:
        - docker-compose up -d
        - docker exec mspass-worker /usr/local/spark/bin/run-example --master spark://mspass-master:7077 SparkPi 10
